### ISSUE TITLE
Search Index rebuild fails with error

### ISSUE THREAD

**Issue by nushkovg** [keitaroinc/ckanext-knowledgehub#311]
Here is the error log:

`2020-02-04 16:38:04,473 ERROR [ckanext.knowledgehub.lib.solr] {'name_or_id': ['Missing value']}
Traceback (most recent call last):
  File "/home/nushkovg/keitaro/knowledgehub/knowledgehub/src/ckanext-knowledgehub/ckanext/knowledgehub/lib/solr.py", line 428, in _next_chunk
    data = cls._get_before_index()(result.__dict__)
  File "/home/nushkovg/keitaro/knowledgehub/knowledgehub/src/ckanext-knowledgehub/ckanext/knowledgehub/model/visualization.py", line 29, in before_index
    {'id': package_id, 'include_tracking': True})
  File "/home/nushkovg/keitaro/knowledgehub/knowledgehub/src/ckan/ckan/logic/__init__.py", line 464, in wrapped
    result = _action(context, data_dict, **kw)
  File "/home/nushkovg/keitaro/knowledgehub/knowledgehub/src/ckan/ckan/logic/action/get.py", line 972, in package_show
    name_or_id = data_dict.get("id") or _get_or_bust(data_dict, 'name_or_id')
  File "/home/nushkovg/keitaro/knowledgehub/knowledgehub/src/ckan/ckan/logic/__init__.py", line 529, in get_or_bust
    raise ValidationError(errors)
ValidationError: {'name_or_id': ['Missing value']}
2020-02-04 16:38:04,474 ERROR [ckanext.knowledgehub.lib.solr] Failed to build index for <Visualization id=b75da873-68a4-4e1a-a66a-6847bfc29599 resource_id=d0b3e35a-45cb-4c58-9352-912a1a7ae752 title=Data Explorer description= view_type=recline_view order=0 config={}>. Error: {'name_or_id': ['Missing value']}`

**Comment by vladoohr** [comment]
@nushkovg it should be fixed in https://github.com/keitaroinc/ckanext-knowledgehub/pull/312

**Comment by nushkovg** [comment]
Tested it and I can confirm that it's working. Closing the issue.
